apiVersion: v1
kind: Service
metadata:
  name: gfj-backend
  namespace: gfj-app
spec:
  selector:
    app: gfj-backend
  ports:
    - protocol: TCP
      port: 8081       # Service port
      targetPort: 8081 # Container port
  type: ClusterIP
